# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f6cd634ff335d66f44256806faf89eb3991573bdf6ce53bcfea0ae52eb87c9eef093fed40df57b1da3532b5c2c9acb49b277305f0db909418f6af4bc7bccd251

test:
  secret_key_base: e95c48695feceef7381a2da8ffd5795e46607b49d2f52c056253e2461a1b35fc6091f9473e32d97c26dd1a5e52b6ccc6a02814350c996aba1ccfcf2f693a6f78

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
